Repository dry-rb/dry-schema, pull requests merged in 2019-04, with the labels that each got.

#115 Add support for `array(:hash) { ... }` shortcut
  lib/dry/schema/macros/array.rb
  spec/integration/schema/macros/array_spec.rb
Labels: enhancement, feature

#116 Wrap whole validation result with result monad
  lib/dry/schema/extensions/monads.rb
  spec/extensions/monads/result_spec.rb
Labels: enhancement

#117 Support for type specs in each
  lib/dry/schema/macros/each.rb
  spec/integration/schema/macros/each_spec.rb
Labels: feature

#103 Add ability to redefine reused schema
  lib/dry/schema/macros/schema.rb
  spec/integration/schema/reusing_schema_spec.rb
Labels: feature
