Repository dry-rb/dry-schema, pull requests merged in 2020-03, with the labels that each got.

#257 Support callbacks in nested schemas
  lib/dry/schema/constants.rb
  lib/dry/schema/dsl.rb
  lib/dry/schema/macros/core.rb
  lib/dry/schema/macros/schema.rb
  lib/dry/schema/macros/value.rb
  lib/dry/schema/processor.rb
  lib/dry/schema/processor_steps.rb
  lib/dry/schema/result.rb
  lib/dry/schema/step.rb
  spec/integration/schema/steps_spec.rb
  spec/integration/schema_spec.rb
  spec/unit/dry/schema/step_spec.rb
Labels: enhancement

#261 Raise ArgumentError if DSL parent configs differ
  lib/dry/schema/dsl.rb
  spec/unit/dry/schema/dsl_spec.rb
Labels: enhancement

#262 Add :info extension
  lib/dry/schema/extensions.rb
  lib/dry/schema/extensions/info.rb
  lib/dry/schema/extensions/info/schema_compiler.rb
  spec/extensions/info/schema_spec.rb
Labels: feature

#260 Unexpected keys errors
  config/errors.yml
  lib/dry/schema/config.rb
  lib/dry/schema/constants.rb
  lib/dry/schema/dsl.rb
  lib/dry/schema/key.rb
  lib/dry/schema/key_coercer.rb
  lib/dry/schema/key_map.rb
  lib/dry/schema/key_validator.rb
  lib/dry/schema/message_compiler.rb
  lib/dry/schema/processor.rb
  lib/dry/schema/result.rb
  spec/integration/schema/unexpected_keys_spec.rb
  spec/unit/dry/schema/key_map_spec.rb
Labels: feature

#276 Extend negated predicates with the logic operator API
  lib/dry/schema/predicate.rb
  spec/integration/schema/not_spec.rb
Labels: bug
